file "$(ALLMOTION)/db/allmotion_motor.db" {
pattern
 {   Sys,        Dev, Ax,      DESC, DTYP,    DIR, VELO,  VBAS,  ACCL,  BDST, BVEL,  BACC,  PORT, ADDR, MRES,	PREC,   EGU,   DHLM,  DLLM,   INIT,  ALIAS }
 {XF:10IDD-ES, Ez4:1,  1, "an2cth",  asynMotor, 0, 20.64, 20.64, 0.035, 0,    20.64, 0.035, ALM1, 0,    1.300e-3,   3,    urad,  300,   -300,   0,  "an2cth" }
 {XF:10IDD-ES, Ez4:1,  2, "an2cchi", asynMotor, 0, 0.209, 0.209, 0.035, 0,    0.209, 0.035, ALM1, 1,    2.09375e-4, 3,    deg,   0.5,   -0.5,   0,  "an2cchi" }
 {XF:10IDD-ES, Ez4:1,  3, "an2wth",  asynMotor, 0, 20.64, 20.64, 0.035, 0,    20.64, 0.035, ALM1, 2,    1.291e-3,   3,    urad,  300,   -300,   0,  "an2wth" }
 {XF:10IDD-ES, Ez4:1,  4, "an2wchi", asynMotor, 0, 0.209, 0.209, 0.035, 0,    0.209, 0.035, ALM1, 3,    2.09375e-4, 3,    deg,   0.5,   -0.5,   0,  "an2wchi" }
}

# an2cchi,an2cchi Move Current=0.8A; They are set during ioc restart